import sys
import os
import json
from state_manager import StateManager
from prp_forge import PRPForge
from task_dispatcher import TaskDispatcher

def main() -> None:
    """Main entry point for the Sovereign Context Engineering Workspace orchestrator.

    Determines the current session's role (SOVEREIGN, WORKER, or IDLE) based on
    the workspace state, and executes the corresponding protocol logic.

    Returns:
        None
    """
    manager = StateManager()
    role = manager.determine_session_role()

    print(f"--- SOVEREIGN CONTEXT ENGINEERING WORKSPACE ---")
    print(f"Session Waking Up.")
    print(f"Determined Role: {role}")
    print(f"-----------------------------------------------")

    if role == "SOVEREIGN":
        print("Executing SOVEREIGN Protocol (Session 0)...")
        unprocessed = manager.get_unprocessed_context()
        print(f"Found {len(unprocessed)} unprocessed context files.")
        print("Action required: Parse context, generate PRPs, and delegate tasks.")

        forge = PRPForge()
        dispatcher = TaskDispatcher()

        for target_file in unprocessed:
            filename = os.path.basename(target_file)
            print(f"Processing context: {filename}")

            raw_intent = forge.extract_intent(target_file)
            prp_data, prp_id = forge.generate_prp(raw_intent, filename)
            prp_path = forge.save_prp(prp_data, prp_id)
            print(f"Generated Cognitive Contract: {prp_path}")

            task_path = dispatcher.dispatch_task(prp_path)
            print(f"Dispatched Task: {task_path}")

            manager.mark_context_processed(filename)
            print("Marked context as processed in StateManager.")

    elif role == "WORKER":
        print("Executing WORKER Swarm Protocol (Session 1-N)...")
        tasks = manager.get_pending_tasks()
        print(f"Found {len(tasks)} pending tasks in /delegated_tasks/.")
        print("Action required: Claim task, execute strictly to PRP constraints, and commit artifact.")

        for target_task in tasks:
            print(f"Claiming task: {target_task}")

            task_content = manager.claim_task(target_task)
            task_data = json.loads(task_content)
            prp_ref = task_data.get("prp_reference")

            with open(prp_ref, 'r') as f:
                prp_data = json.load(f)

            print(f"Executing PRP: {prp_data['metadata']['id']}")

            artifact_content = f"# Execution Artifact for {prp_data['metadata']['id']}\n\n"
            artifact_content += "This artifact was deterministically generated by the Worker Swarm.\n"
            artifact_content += f"Source Lineage: {prp_data['metadata']['drp_lineage']}\n"

            artifact_name = f"ARTIFACT_{prp_data['metadata']['id']}.md"

            manager.complete_task(target_task, artifact_content, artifact_name)
            print(f"Task completed. Artifact saved to /completed_artifacts/{artifact_name}")

    else:
        print("Workspace is IDLE. No pending tasks and no new context.")
        print("Action required: Wait for next scheduled run or ingest new context.")

if __name__ == "__main__":
    main()
