import os
import random
import json
from system_logic.state_manager import StateManager

def execute_task(manager: StateManager, target_task: str, commit: bool = True) -> None:
    """Executes a single task based on its Cognitive Contract (PRP).

    Args:
        manager: The StateManager instance.
        target_task: The file path to the task to execute.
    """
    print(f"Claiming task: {target_task}")

    # 1. Read Task
    try:
        task_content, claimed_task_path = manager.claim_task(target_task)
    except FileNotFoundError:
        print(f"Task {target_task} was already claimed by another worker.")
        return
    task_data = json.loads(task_content)
    prp_ref = task_data.get("prp_reference")

    # Validate prp_ref to prevent arbitrary file read (path traversal)
    if not prp_ref:
        raise ValueError("Missing prp_reference in task data.")

    abs_prp_ref = os.path.realpath(prp_ref)
    contracts_dir = os.path.realpath(manager.contracts_dir)
    if os.path.commonpath([abs_prp_ref, contracts_dir]) != contracts_dir:
        raise PermissionError(f"Access denied: {prp_ref} is outside the allowed contracts directory.")

    # 2. Read PRP
    with open(abs_prp_ref, 'r') as f:
        prp_data = json.load(f)

    print(f"Executing PRP: {prp_data['metadata']['id']}")

    is_cipher_task = "CIPHER" in prp_data.get("metadata", {}).get("drp_lineage", "").upper() or \
                     "CIPHER" in prp_data.get("metadata", {}).get("id", "").upper()

    cfdi_threshold = 0.08 if is_cipher_task else 0.15

    # 3. Simulate CFDI Calculation (Confidence-Fidelity Divergence Index)
    # In a real system, this would be computed via cross-encoder divergence tracking
    cfdi_score = round(random.uniform(0.01, 0.25), 3)
    print(f"Calculated CFDI Score: {cfdi_score}")

    if cfdi_score > cfdi_threshold:
        print(f"CFDI Threshold exceeded (>{cfdi_threshold}). Triggering CFDI Brake and Epistemic Escrow.")
        conflict_reason = f"Simulated schema divergence detected in {prp_data['metadata']['id']}."
        ticket_path = manager.escrow_task(claimed_task_path, cfdi_score, conflict_reason, is_cipher_task=is_cipher_task)
        print(f"Task quarantined. Escrow Ticket generated: {ticket_path}")
        return

    # 4. Simulate Petzold Sequence Execution
    artifact_content = f"# Execution Artifact for {prp_data['metadata']['id']}\n\n"
    artifact_content += "This artifact was deterministically generated by the Worker Swarm.\n"
    artifact_content += f"Source Lineage: {prp_data['metadata']['drp_lineage']}\n\n"

    if is_cipher_task:
        print("+++PetzoldSequence(phase='THINK')")
        artifact_content += "## Phase 1: THINK\n- Threat hypothesis DAG constructed (SilentReasoning active).\n"

        print("+++PetzoldSequence(phase='THREAT_MODEL')")
        artifact_content += "## Phase 2: THREAT_MODEL\n- STRIDE Threat Matrix JSON scaffold populated.\n- Mereology route check executed.\n"

        print("+++PetzoldSequence(phase='AUDIT')")
        artifact_content += "## Phase 3: AUDIT\n- AST traversal initiated.\n- Taint paths verified against STRIDE scaffold.\n- Saga-style compensating transactions evaluated.\n"

        print("+++PetzoldSequence(phase='REPORT')")
        artifact_content += "## Phase 4: REPORT\n- DCCDSchemaGuard enforced on STRIDE_THREAT_MATRIX_v1.2 and AST_VULN_REPORT_v1.1.\n"
        artifact_content += "CIPHER VERDICT: MERGE APPROVED — 0 findings logged.\n"
    else:
        # Standard fallback for non-CIPHER tasks
        artifact_content += "## Execution Log\n- Standard execution completed.\n"

    artifact_name = f"ARTIFACT_{prp_data['metadata']['id']}.md"

    # 5. Complete Task
    manager.complete_task(claimed_task_path, artifact_content, artifact_name, commit=commit)
    print(f"Task completed. Artifact saved to /completed_artifacts/{artifact_name}")

def run_worker() -> None:
    """Executes the worker swarm protocol.

    This function claims a pending task from the delegated tasks directory,
    reads the task and its associated Cognitive Contract (PRP), simulates
    the execution of the task to generate an artifact, and then marks the
    task as complete.

    Returns:
        None
    """
    manager = StateManager()

    tasks = manager.get_pending_tasks()
    if not tasks:
        print("No pending tasks.")
        return

    target_task = tasks[0]
    execute_task(manager, target_task)

if __name__ == "__main__":
    run_worker()
